/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/metaplex-foundation/kinobi
 */

import {
  Context,
  Pda,
  PublicKey,
  RpcAccount,
  RpcGetAccountsOptions,
  assertAccountExists,
  publicKey as toPublicKey,
} from '@metaplex-foundation/umi';
import { Mint, deserializeMint } from './mint';
import { Token, deserializeToken } from './token';
import { Multisig, deserializeMultisig } from './multisig';

export type Token2022Account = Mint | Token | Multisig;

export function deserializeToken2022Account(
  rawAccount: RpcAccount
): Token2022Account {
  const data = rawAccount.data;
  if (data.length === 82) {
    return deserializeMint(rawAccount);
  }
  if (data.length === 165) {
    return deserializeToken(rawAccount);
  }
  if (data.length === 355) {
    return deserializeMultisig(rawAccount);
  }
  throw new Error(
    'The provided account could not be identified as a token2022 account.'
  );
}

export async function fetchAllToken2022Accounts(
  context: Pick<Context, 'rpc'>,
  publicKeys: Array<PublicKey | Pda>,
  options?: RpcGetAccountsOptions
): Promise<Token2022Account[]> {
  const maybeAccounts = await context.rpc.getAccounts(
    publicKeys.map((key) => toPublicKey(key, false)),
    options
  );
  return maybeAccounts.map((maybeAccount) => {
    assertAccountExists(maybeAccount);
    return deserializeToken2022Account(maybeAccount);
  });
}

export async function safeFetchAllToken2022Accounts(
  context: Pick<Context, 'rpc'>,
  publicKeys: Array<PublicKey | Pda>,
  options?: RpcGetAccountsOptions
): Promise<(Token2022Account | null)[]> {
  const maybeAccounts = await context.rpc.getAccounts(
    publicKeys.map((key) => toPublicKey(key, false)),
    options
  );
  return maybeAccounts.map((maybeAccount) => {
    if (!maybeAccount.exists) return null;
    return deserializeToken2022Account(maybeAccount);
  });
}
